### ISSUE TITLE
create an icon to overlay an arbitrary input field

### ISSUE THREAD

**Issue by dangerouse** [cloudsponge/better-sharing-js#5]
@dimitarangelkov I'd like a square SVG icon that can be overlaid on an input field as mocked up here:

![image.png](https://images.zenhubusercontent.com/58910d6951aa2c3057732d15/f964d713-e368-41f1-818c-be28c00e9849)

**Comment by dimitarangelkov** [comment]
@dangerouse the SVGs are in the [Archive.zip](https://github.com/cloudsponge/better-sharing-js/files/5300212/Archive.zip)

![icon-1](https://user-images.githubusercontent.com/14825668/94580627-cfc91d00-0282-11eb-99c9-60d353b6a5cd.png)
![icon-2](https://user-images.githubusercontent.com/14825668/94580655-d6579480-0282-11eb-98a8-05c6a78682b1.png)
![icon-3](https://user-images.githubusercontent.com/14825668/94580670-d9eb1b80-0282-11eb-8a84-18bcf4ceff0c.png)
![icon-4](https://user-images.githubusercontent.com/14825668/94580685-de173900-0282-11eb-875b-d811ed618c20.png)

Let me know if you need anything else

**Comment by dimitarangelkov** [comment]
FYI I don't have permissions to move the issue to the other pipelines.
